In [1]:
import geopandas as gpd

# Replace 'path/to/your/shapefile.shp' with the path to your shapefile
shapefile_path = "showcase/shp/fields17.shp"

# Load the shapefile using GeoPandas
gdf = gpd.read_file(shapefile_path)

In [3]:
# Extract polygons from the 'geometry' column
polygons = gdf["geometry"]
tolat_area = 0
# Iterate through the polygons and print them
for i, polygon in enumerate(polygons):
    #print(f"Polygon {i}:", polygon)
    tolat_area += polygon.area

In [12]:
gdf

,if,labelid,label,doystart,doyend,geometry
0,298333,24,winter rye,None,None,"POLYGON ((675403.782 5377053.487, 675453.713 5..."
1,298342,3,meadow,None,None,"POLYGON ((674687.461 5377610.498, 674684.752 5..."
2,298348,22,winter wheat,None,None,"POLYGON ((675133.592 5376424.068, 675101.481 5..."
3,298355,26,maize,None,None,"POLYGON ((674220.155 5376873.121, 674194.144 5..."
4,298358,22,winter wheat,None,None,"POLYGON ((674131.018 5377159.519, 674148.505 5..."
...,...,...,...,...,...,...
89110,298283,23,winter barley,None,None,"POLYGON ((674470.556 5377668.047, 674502.395 5..."
89111,298296,26,maize,None,None,"POLYGON ((674090.194 5377528.966, 673976.348 5..."
89112,298297,26,maize,None,None,"POLYGON ((674018.030 5377766.075, 674053.876 5..."
89113,298298,8,hop,None,None,"POLYGON ((673973.083 5377384.842, 673962.422 5..."
89114,298318,26,maize,None,None,"POLYGON ((675912.038 5377835.707, 675905.985 5..."

In [5]:
tolat_area /1000000

2015.164997562326